### PR TITLE
Feature/us 048 migrate post operation to login

### PR DESCRIPTION
**Pull request by Sergio-Dom**
The login logic from **at-sce-api** was migrated to **at-sso-ap**i

### CODE REVIEW

**Review by luisgalindoluna — COMMENTED** [review]
So far looks fine, but I'm pretty this has JUnits and you didn't migrate any. 
Also there's a PR in at-sce-api that has a few changes for the Login method so you'll have to move that as well. Keep an eye out on that PR it's from Alejandra.

**Comment by Sergio-Dom** [comment]
> 
> 
> So far looks fine, but I'm pretty this has JUnits and you didn't migrate any.
> Also there's a PR in at-sce-api that has a few changes for the Login method so you'll have to move that as well. Keep an eye out on that PR it's from Alejandra.

I'll be watchfull the PR related with Login functionality and take care the JUnit test

**Comment by ivanflores15** [comment]
please rebase to current develop reference

**Review by luisgalindoluna — COMMENTED** [review]
Just resolve conflicts and add JUnits so this can be approved.

**Pull request closed without merging**
